services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test

volumes:
  postgres_data: